### ISSUE TITLE
device in use

### ISSUE THREAD

**Issue by Pfirsichdrache** [Lauriethefish/ModsBeforeFriday#16] opened 2024-06-11 15:54 UTC
![Screenshot 2024-06-11 165355](https://github.com/Lauriethefish/ModsBeforeFriday/assets/164479127/56c28f76-cbcf-4c46-919e-3e416389dc20)

i tried everything but it dont work and i didnt even have sidequest downloaded

**Comment by Lauriethefish** [comment] 2024-06-28 15:08
Duplicate of #9

**Closed by Lauriethefish** 2024-06-28 15:08 UTC
