### ISSUE TITLE
Connection issues on v65

### ISSUE THREAD

**Issue by jxnxsdev** [Lauriethefish/ModsBeforeFriday#13] opened 2024-05-30 22:46 UTC
Users on v65 seem to be facing connection issues with mbf. It’ll always report device in use when selecting it. No adb running, consistent across browsers and devices.

**Comment by Lauriethefish** [comment] 2024-06-25 15:01
I am on v65 and the connection is working fine.
Do you have a consistent way to reproduce this problem?

**Comment by jxnxsdev** [comment] 2024-06-25 16:45
Not really. The problem seems to be inconsistent and only happens to a user now and then.

**Comment by Lauriethefish** [comment] 2024-06-25 16:46
Unfortunately I can't fix it without a consistent way to reproduce it. I will add more logging to try to narrow down the problem a little.

**Comment by Lauriethefish** [comment] 2024-06-29 14:14
Additional logging has been added, lmk if you get a different error.

**Comment by tuxfamily** [comment] 2024-07-16 09:34
This is my first time using MBF, and I'm having the same issue (same popup as shown in #9). 

I encountered the error on my Mac, but since it's a dev machine, conflicts may have been possible. 
So, I tried it on a fresh Linux install (Ubuntu 24.04) with only Chromium and ADB, but no luck.

I thought maybe there was a conflict with [Quest Games Optimizer](https://anagan79.itch.io/quest-games-optimizer/), as it uses ADB internally. I uninstalled it, restarted, tried again on the fresh Linux setup, but still got the same message.

I've tried with the `?dev=true` query parameter but it does not help, there is nothing more in the (browser) console.

How can I help you solving this issue?

**Comment by Zexlar69** [comment] 2024-07-17 05:01
This is my first time using MBF as well and I'm having the same issue as stated above and in #9 

Issue occurred on my Windows 10 Laptop, I had installed ADB following Oculus's guide then attempted connecting my Quest 2 to install.

Issue persisted, same screen the headset is detected and the files are accessible to the laptop.

Attempted uninstalling Beat Saber and ADB, and restarting both the Laptop and Quest 2 in question to no avail.

**Comment by Lauriethefish** [comment] 2024-07-17 09:34
Replying to @tuxfamily here, going through in order:
> I've tried with the ?dev=true query parameter but it does not help, there is nothing more in the (browser) console.
Yeah, this parameter doesn't relate to debug info (i.e. doesn't help development of MBF itself) but is for mod developers to be able to bypass the version check in order to install test versions of mods before all the core mods come out for a particular version.
> I assume that simply running 'adb devices' in the terminal or having a process polling for devices may lead to this error.
Yes, this is the case. If there is an `adb` daemon running on your computer, then it will attempt to connect to the quest first, which prevents MBF from connecting to it. (it "claims" the USB connection)

If you have the same issue on a windows PC, it provides instructions to use `taskkill` to get rid of the `adb` process, and close any apps that might be trying to start a new ADB process.
Running `adb kill-server` also does the trick.

**Comment by Lauriethefish** [comment] 2024-07-17 09:36
Replying to @Zexlar69 
If you're on a windows PC, you should receive a screen more similar to this:
![Device in use prompt on windows](https://github.com/user-attachments/assets/870968b3-eec1-46ee-9aac-473e73cbb39e)

Did you try closing sidequest and running the commands it provided?

**Comment by Lauriethefish** [comment] 2024-08-20 12:05
I'm going to close this since I still cannot reproduce it.
I'm presuming it's some issue with drivers on individual machines or outdated browsers.

If somebody can still reproduce this, lmk and I can reopen. It would be great if you could reproduce it *on a fresh install of your OS* so I can actually investigate it.

**Closed by Lauriethefish** 2024-08-20 12:05 UTC
